# Generated by Django 5.1.7 on 2025-03-24 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('age', models.IntegerField(default=False, validators=[django.core.validators.MaxValueValidator(110), django.core.validators.MinValueValidator(1)])),
                ('number_of_pets', models.IntegerField(default=0)),
            ],
        ),
    ]
