# Generated by Django 5.1.7 on 2025-03-25 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_owners_app', '0002_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('age', models.IntegerField(default=False, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)])),
                ('species', models.CharField(default=False, max_length=255)),
                ('vaccinated', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
