# Generated by Django 5.1.7 on 2025-03-25 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_owners_app', '0003_bird'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('age', models.IntegerField(default=False, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)])),
                ('breed', models.CharField(max_length=50)),
                ('vaccinated', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exotic_Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('age', models.IntegerField(default=False, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)])),
                ('type_of_animal', models.CharField(max_length=50)),
                ('vaccinated', models.BooleanField(default=False)),
                ('region_of_origin', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
