# Generated by Django 5.1.7 on 2025-03-26 02:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_owners_app', '0004_dog_exotic_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='name',
            field=models.CharField(max_length=75, validators=[django.core.validators.RegexValidator(message='Invalid pet name. First letter must be capitalized.', regex='^[A-Z][a-z]+(?: [A-Z][a-z]+)*$')]),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=75, validators=[django.core.validators.RegexValidator(message='Invalid pet name. First letter must be capitalized.', regex='^[A-Z][a-z]+(?: [A-Z][a-z]+)*$')]),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=75, validators=[django.core.validators.RegexValidator(message='Invalid pet name. First letter must be capitalized.', regex='^[A-Z][a-z]+(?: [A-Z][a-z]+)*$')]),
        ),
        migrations.AlterField(
            model_name='exotic_animal',
            name='name',
            field=models.CharField(max_length=75, validators=[django.core.validators.RegexValidator(message='Invalid pet name. First letter must be capitalized.', regex='^[A-Z][a-z]+(?: [A-Z][a-z]+)*$')]),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=75, validators=[django.core.validators.RegexValidator(message='Invalid name. Name must but in First Last format.', regex='^[A-Z][a-z]+ [A-Z][a-z]+$')]),
        ),
    ]
